### ISSUE TITLE
Thanks for your codes! How to Compare with ABMDRNet and MMNet?

### ISSUE THREAD

**Issue by LiuzhuForFun** [MathLee/LASNet#2]
I cannot find any codes about these two models. Thanks for your contribution again!

**Comment by MathLee** [comment]
You can leave a mailbox for me. I will mail the segmentation maps of ABMDRNet and MMNet to you.

**Comment by LiuzhuForFun** [comment]
1300990625@qq.com thanks alot, if you has the segmentation map about EGFNet (AAAI 21), please pack them all!

**Comment by MathLee** [comment]
Ok, got it.

**Comment by LiuzhuForFun** [comment]
Furthermore, do you have their training codes or scripts of models? Thanks!

**Comment by MathLee** [comment]
I don't have their training codes. I directly mail these authors to achieve segmentation maps.

**Comment by LiuzhuForFun** [comment]
好的，表里的数值结果都是用给的segentation map重新算的吗?

**Comment by MathLee** [comment]
Actually, I got the performance from their original papers.

**Comment by LiuzhuForFun** [comment]
Thanks a lot ! I will follow/cite your papers and put more attention to learn your excellent literature!
