### ISSUE TITLE
Gradient overflow

### ISSUE THREAD

**Issue by HaoZhang1018** [MathLee/LASNet#3]
When I starting to run train_LASNet.py,  warnings related to apex appear in the early stage:
Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 1024.0
Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 512.0
Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 256.0.

I wonder if the authors have encountered this problem. Thanks a lot!

**Comment by MathLee** [comment]
These warnings are ok.
